services:

  apache_php_proyecto:

    build:
      context: .docker
      dockerfile: Dockerfile
    container_name: php_apache_examen

    volumes:
      - ./src:/var/www/html
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/xdebug/debug.ini:/usr/local/etc/php/conf.d/debug.ini

    expose:
      - 80
    ports:
      - 8085:80
    networks:
      - examen
    links:
      - mariadb

    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadb:
    image: mariadb:latest
    restart: on-failure

    ports:
      - 3310:3306

    networks:
      - examen

    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: examen
      MARIADB_USER: alumno
      MARIADB_PASSWORD: alumno

    command:
      --default-authentication-plugin=mysql_native_password

networks:
  examen:
    name: examen
    driver: bridge